In [2]:
import json
import pandas as pd

In [3]:
# Ratings given

emoji_map = {
    "1️⃣":1, "2️⃣":2, "3️⃣":3, "4️⃣":4, "5️⃣":5,
  "6️⃣":6, "7️⃣":7, "8️⃣":8, "9️⃣":9, "🔟":10
}

MIN_COUNT = 10
     
with open("food.json", encoding="utf-8") as f:
    data = json.load(f)

rows = []

for msg in data["messages"]:
    for reaction in msg["reactions"]:
        if reaction["emoji"]["raw"] in emoji_map.keys():
            rating = reaction["score"]
            for user in reaction["users"]:
                rows.append({
                    "critic": user["username_at_time"],
                    "rating": rating
                })


critic_df = pd.DataFrame(rows)

critic_df = (
    critic_df.groupby("critic")
    .agg(
        avg_given=("rating", "mean"),
        count=("rating", "count"),
        std=("rating", "std")
    )
)

critic_df["z_score"] = (
    (critic_df["avg_given"] - critic_df["avg_given"].mean())
    / critic_df["avg_given"].std()
)

critic_df.query(f"count >= {MIN_COUNT}").sort_values("z_score", ascending=False)

                          avg_given  count       std   z_score
critic
ivisumon                   7.356250    160  2.084223  0.367452
truckforerbastian          7.068182     44  2.500211  0.233117
boratsagdiyev5149          6.873418     79  3.039767  0.142292
coalhawk                   6.444444    126  2.815828 -0.057752
jesper7177                 6.316742    221  2.276189 -0.117303
stoffe1                    6.089552     67  3.028808 -0.223249
konrad_certified_rizzler   5.770492    183  3.031302 -0.372037
keisernavdombaas           4.300000    150  3.397097 -1.057773

In [4]:
# Ratings received

from collections import defaultdict

emoji_map = {
    "1️⃣":1, "2️⃣":2, "3️⃣":3, "4️⃣":4, "5️⃣":5,
  "6️⃣":6, "7️⃣":7, "8️⃣":8, "9️⃣":9, "🔟":10
}

MIN_COUNT = 15
              
with open("food.json", encoding="utf-8") as f:
    data = json.load(f)


users = defaultdict(lambda: defaultdict(list))

for msg in data["messages"]:
    chef = msg["author"]["username_at_time"]
    for reaction in msg["reactions"]:
        raw = reaction["emoji"]["raw"]
        if raw in emoji_map:
            rating = emoji_map[raw]
            for user in reaction["users"]:
                critic = user["username_at_time"]
                users[chef][critic].append(rating)

rows = []
for chef, critics in users.items():
    for critic, ratings in critics.items():
        for r in ratings:
            rows.append({
                "chef": chef,
                "critic": critic,
                "rating": r
            })


chef_df = pd.DataFrame(rows)

chef_df = (
    chef_df.groupby("chef")
    .agg(
        avg_received=("rating", "mean"),
        count=("rating", "count"),
        std=("rating", "std"),
        var=("rating", "var")
    )
)

chef_df.query(f"count >= {MIN_COUNT}").sort_values("avg_received", ascending=False)

                          avg_received  count       std        var
chef
oddbjorn6810                  7.956522     23  1.551488   2.407115
stoffe1                       6.578313     83  2.384505   5.685865
boratsagdiyev5149             6.571429    154  2.748397   7.553688
jesper7177                    6.367347    147  3.162454  10.001118
coalhawk                      6.253333     75  2.242666   5.029550
kulmann123                    6.170370    135  2.755025   7.590160
truckforerbastian             6.126126    111  3.000355   9.002129
ivisumon                      5.768519    216  2.977767   8.867097
konrad_certified_rizzler      5.684211     38  3.647326  13.302987
lordloke01                    5.619048     21  2.479439   6.147619

In [5]:
# Dishes made per chef

MIN_COUNT = 5

dishes_per_chef = defaultdict(int)

with open("food.json", encoding="utf-8") as f:
    data = json.load(f)


for msg in data["messages"]:
    chef = msg["author"]["username_at_time"]
    dishes_per_chef[chef] += 1

flattened = []
for el in dishes_per_chef:
    flattened.append({"chef": el, "dishes": dishes_per_chef[el]})

dish_df = (
    pd.DataFrame(flattened)
    .query(f"dishes >= {MIN_COUNT}")
    .sort_values("dishes", ascending=False)
    .reset_index(drop=True)
    .set_index("chef")
)

dish_df

                          dishes
chef
ivisumon                      66
jesper7177                    50
boratsagdiyev5149             41
kulmann123                    35
stoffe1                       32
truckforerbastian             26
coalhawk                      24
konrad_certified_rizzler      17
oddbjorn6810                   7

In [6]:
import statistics

# Individual dishes

dishes = []

MIN_COUNT = 5

for msg in data["messages"]:
    
    ratings = [
        emoji_map[reaction["emoji"]["raw"]]
        for reaction in msg["reactions"]
        if reaction["emoji"]["raw"] in emoji_map
        for _ in reaction["users"]
    ]

    count = len(ratings)

    if count >= 2:
        avg_rating = statistics.mean(ratings)
        sd = statistics.stdev(ratings)
    elif count == 1:
        avg_rating = ratings[0]
        sd = 0.0
    else:
        avg_rating = None
        sd = None

    dishes.append({
        "dish": msg["content"] or "<no description>",
        "chef": msg["author"]["username_at_time"],
        "images": [img["url"] for img in msg["images"]],
        "ratings": ratings,
        "avg_rating": avg_rating,
        "sd": sd,
        "count": count
    })

df = (
    pd.DataFrame(dishes)
    .query(f"count >= {MIN_COUNT}")
    .sort_values("avg_rating", ascending=False)
    # .sort_values("avg_rating")
    # .sort_values("sd", ascending=False)
    # .sort_values("count", ascending=False)
)

df.head(10)

# for el in df.head(5)["images"]:
#     print(el)

,dish,chef,images,ratings,avg_rating,sd,count
8,Spiste den rå,ivisumon,[https://cdn.discordapp.com/attachments/932063...,"[10, 10, 10, 10, 10, 10]",10.000000,0.000000,6
250,<no description>,kulmann123,[https://cdn.discordapp.com/attachments/932063...,"[10, 10, 10, 10, 10]",10.000000,0.000000,5
90,<no description>,truckforerbastian,[https://cdn.discordapp.com/attachments/932063...,"[10, 10, 10, 10, 10]",10.000000,0.000000,5
112,Food pic,etr91,[https://cdn.discordapp.com/attachments/932063...,"[10, 10, 10, 10, 10]",10.000000,0.000000,5
95,<no description>,truckforerbastian,[https://cdn.discordapp.com/attachments/932063...,"[10, 10, 10, 10, 9, 9, 9]",9.571429,0.534522,7
44,Ramen,jesper7177,[https://cdn.discordapp.com/attachments/932063...,"[10, 9, 9, 9, 8]",9.000000,0.707107,5
164,<no description>,coalhawk,[https://cdn.discordapp.com/attachments/932063...,"[8, 8, 8, 10, 10]",8.800000,1.095445,5
20,<no description>,truckforerbastian,[https://cdn.discordapp.com/attachments/932063...,"[10, 10, 10, 10, 4, 8]",8.666667,2.422120,6
78,<no description>,boratsagdiyev5149,[https://cdn.discordapp.com/attachments/932063...,"[10, 10, 8, 8, 8, 8]",8.666667,1.032796,6
14,Saken er biff,boratsagdiyev5149,[https://cdn.discordapp.com/attachments/932063...,"[8, 8, 10, 9, 9, 7]",8.500000,1.048809,6

In [8]:
# rating of others compared to mean

emoji_map = {
    "1️⃣":1, "2️⃣":2, "3️⃣":3, "4️⃣":4, "5️⃣":5,
  "6️⃣":6, "7️⃣":7, "8️⃣":8, "9️⃣":9, "🔟":10
}

MIN_COUNT = 10
              
with open("food.json", encoding="utf-8") as f:
    data = json.load(f)

rows = []

for msg in data["messages"]:
    for reaction in msg["reactions"]:
        raw = reaction["emoji"]["raw"]
        if raw in emoji_map:
            rating = emoji_map[raw]
            for user in reaction["users"]:
                rows.append({
                    "cook": msg["author"]["username_at_time"],
                    "critic": user["username_at_time"],
                    "rating": rating
                })

df = pd.DataFrame(rows)

# baselines
global_avg = df["rating"].mean()
critic_avg = df.groupby("critic")["rating"].mean()
cook_avg = df.groupby("cook")["rating"].mean()

# pair stats
pair_avg = (
    df
    .groupby(["critic","cook"])
    .agg(
        mean_rating=("rating","mean"),
        count=("rating","count")
    )
    .reset_index()
)

# attach baselines to pairs
pair_avg["critic_avg"] = pair_avg["critic"].map(critic_avg)
pair_avg["cook_avg"] = pair_avg["cook"].map(cook_avg)

# bias
pair_avg["bias"] = (
    pair_avg["mean_rating"]
    - pair_avg["critic_avg"]
    - pair_avg["cook_avg"]
    + global_avg
)

pair_avg.query(f"count >= {MIN_COUNT}").sort_values("bias", ascending=False).head(10)

,critic,cook,mean_rating,count,critic_avg,cook_avg,bias
104,keisernavdombaas,kulmann123,8.615385,13,4.300000,6.170370,4.325659
153,stoffe1,jesper7177,8.285714,14,6.089552,6.367347,2.009460
18,boratsagdiyev5149,truckforerbastian,8.727273,11,6.873418,6.126126,1.908374
96,keisernavdombaas,boratsagdiyev5149,5.920000,25,4.300000,6.571429,1.229217
78,jesper7177,ivisumon,6.803571,56,6.316742,5.768519,0.898956
75,jesper7177,coalhawk,7.235294,17,6.316742,6.253333,0.845864
22,coalhawk,boratsagdiyev5149,7.647059,17,6.444444,6.571429,0.811831
55,ivisumon,jesper7177,8.235294,34,7.356250,6.367347,0.692342
120,konrad_certified_rizzler,ivisumon,5.729730,37,5.770492,5.768519,0.371365
91,jesper7177,truckforerbastian,6.571429,21,6.316742,6.126126,0.309206